# Generated by Django 3.1.7 on 2021-06-04 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0002_auto_20210604_2344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="scenario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="scenario.scenario",
            ),
        ),
    ]
