# Generated by Django 3.1.7 on 2021-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0007_auto_20210608_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterModelOptions(
            name='worldinfo',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
