# Generated by Django 3.1.7 on 2021-06-09 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0008_auto_20210609_1600"),
        ("accounts", "0005_auto_20210609_1648"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="folder",
        ),
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="accounts.folder",
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="scenarios",
            field=models.ManyToManyField(
                related_name="added_to", to="scenario.Scenario"
            ),
        ),
    ]
