# Generated by Django 3.1.7 on 2021-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210712_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True, help_text='Summary of the folder contents.', max_length=400),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(help_text='Folder name.', max_length=70),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Parent folders. Notice that a folder can have parent folders from multiple users.', related_name='children', to='accounts.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('published', 'Published')], db_index=True, default='private', help_text='Wheter it can be seen by other users or not.', max_length=10),
        ),
    ]
