# Generated by Django 3.1.7 on 2021-07-12 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0011_auto_20210712_2031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20210712_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='scenarios',
            field=models.ManyToManyField(blank=True, help_text="Scenarios added to the folder, could be anyone's as long as they are public or the made by the folder owner.", related_name='added_to', to='scenario.Scenario'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(help_text='The creator of the folder.', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
